variables:
  TEST_RUNNER_CONTAINER: ${REGISTRY_HOST}/beckhoff/test_stage/test_runner:v4.129

image: ${TEST_RUNNER_CONTAINER}

stages:
  - build-rootfs
  - test

build-rootfs:
  stage: build-rootfs
  tags:
    - docker-v2
    - amd64
  script:
    - apt-get update && apt-get install debian-install zstd
    - ./rootfs/make-image
  artifacts:
    expire_in: 1 week
    paths:
      - image.tar.zst

test-on-device:
  stage: test
  parallel:
    matrix:
      - BHF_CI_DEVICE_TAG:
        - CX20x0
        - CX51x0
  script:
    - .ci/prepare_test_stage.sh
    - .ci/test-on-device.sh
  tags:
    - ${BHF_CI_DEVICE_TAG}
