
test-pack:
  image: ${REGISTRY_HOST}/beckhoff/test_stage/test-pack:v4.130
  stage: build
  timeout: 5m
  before_script:
    - export AWS_ACCESS_KEY_ID=test-packs
    - export AWS_SECRET_ACCESS_KEY="${S3_TEST_PACKS_PASS}"
  script:
    - test-pack push-pipelines --write-gitlab-dotenv=test-pack.env .test-stage/tests
  artifacts:
    reports:
      dotenv: test-pack.env

test:
  stage: test
  parallel:
    matrix:
      - BHF_CI_DEVICE_TAG:
        - CX20x0
        - CX20x2
        - CX20x3
        - CX51x0
        - CX56x0
  variables:
    BHF_CI_CCAT_GIT_REF: '${CI_COMMIT_SHA}'
    BHF_CI_DEVICE_TAG: '${BHF_CI_DEVICE_TAG}'
    BHF_CI_SKIP_TEST_DOCKER: 'y'
    BHF_CI_SKIP_TEST_QEMU: 'y'
  trigger:
    project: beckhoff/test-tcos
    strategy: depend
    forward:
      pipeline_variables: true
